config: conf/gaussian_kernel_regression_gpt2_fast.yaml
inherit:
- /workspace/code/is_mamba_capable_of_icl/simple_functions/src/conf/base.yaml
model:
  family: gpt2
  n_dims: 20
  n_embd: 64
  n_head: 8
  n_layer: 4
  n_positions: 2048
  remove_pos_embedding: true
out_dir: ../models/gkr_gpt2_fast/a8f8373d-aab3-483b-acb6-72f5291b68e9
test_run: false
training:
  batch_size: 16
  curriculum:
    dims:
      end: 20
      inc: 1
      interval: 2000
      start: 5
    points:
      end: 13
      inc: 2
      interval: 50
      start: 11
  data: gaussian
  data_kwargs: {}
  keep_every_steps: 100000
  learning_rate: 0.0001
  learning_rate_schedule: cosine
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  seed: 1
  task: gaussian_kernel_regression
  task_kwargs: {}
  train_steps: 200
wandb:
  entity: binwenliu-ai-xi-an-jiaotong-university-
  log_every_steps: 100
  name: gkr_gpt2_fast_debug
  notes: ''
  project: in-context-mamba
