_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 6
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 6
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.8.20
            "5": 0.19.9
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
config:
    value: conf/linear_regression_gpt2.yaml
inherit:
    value:
        - /workspace/code/is_mamba_capable_of_icl/simple_functions/src/conf/base.yaml
model:
    value:
        family: gpt2
        n_dims: 20
        n_embd: 256
        n_head: 8
        n_layer: 12
        n_positions: 2048
        remove_pos_embedding: true
out_dir:
    value: ../models/linear_regression/01792bc8-29fb-4d6a-b590-537dcf997170
test_run:
    value: false
training:
    value:
        batch_size: 64
        curriculum:
            dims:
                end: 20
                inc: 1
                interval: 2000
                start: 5
            points:
                end: 41
                inc: 2
                interval: 2000
                start: 11
        data: gaussian
        keep_every_steps: 100000
        learning_rate: 0.0001
        learning_rate_schedule: cosine
        num_tasks: null
        num_training_examples: null
        resume_id: null
        save_every_steps: 1000
        seed: 1
        task: linear_regression
        train_steps: 500001
wandb:
    value:
        entity: binwenliu-ai-xi-an-jiaotong-university-
        log_every_steps: 100
        name: linear_regression_standard
        notes: ""
        project: in-context-mamba
